"""empty message

Revision ID: 5db7882faa78
Revises: 
Create Date: 2022-07-14 19:59:44.311243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db7882faa78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('uuid', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('pharmacies',
    sa.Column('uuid', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('users',
    sa.Column('uuid', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('transactions',
    sa.Column('uuid', sa.String(length=256), nullable=False),
    sa.Column('patient_uuid', sa.String(length=256), nullable=True),
    sa.Column('pharmacy_uuid', sa.String(length=256), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_uuid'], ['patients.uuid'], ),
    sa.ForeignKeyConstraint(['pharmacy_uuid'], ['pharmacies.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.drop_table('TRANSACTIONS')
    op.drop_table('USERS')
    op.drop_table('PATIENTS')
    op.drop_table('PHARMACIES')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PHARMACIES',
    sa.Column('UUID', sa.VARCHAR(length=256), nullable=False),
    sa.Column('NAME', sa.VARCHAR(length=50), nullable=False),
    sa.Column('CITY', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('PATIENTS',
    sa.Column('UUID', sa.VARCHAR(length=256), nullable=False),
    sa.Column('FIRST_NAME', sa.VARCHAR(length=30), nullable=False),
    sa.Column('LAST_NAME', sa.VARCHAR(length=30), nullable=False),
    sa.Column('DATE_OF_BIRTH', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('USERS',
    sa.Column('UUID', sa.VARCHAR(length=256), nullable=False),
    sa.Column('USERNAME', sa.VARCHAR(length=50), nullable=False),
    sa.Column('PASSWORD', sa.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('UUID')
    )
    op.create_table('TRANSACTIONS',
    sa.Column('UUID', sa.VARCHAR(length=256), nullable=False),
    sa.Column('PATIENT_UUID', sa.VARCHAR(length=256), nullable=False),
    sa.Column('PHARMACY_UUID', sa.VARCHAR(length=256), nullable=False),
    sa.Column('AMOUNT', sa.NUMERIC(), nullable=False),
    sa.Column('TIMESTAMP', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['PATIENT_UUID'], ['PATIENTS.UUID'], ),
    sa.ForeignKeyConstraint(['PHARMACY_UUID'], ['PHARMACIES.UUID'], ),
    sa.PrimaryKeyConstraint('UUID')
    )
    op.drop_table('transactions')
    op.drop_table('users')
    op.drop_table('pharmacies')
    op.drop_table('patients')
    # ### end Alembic commands ###
