# Esse workflow irá instalar dependências do Python, executar testes e analisar a qualidade do código

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        flake8 . --exit-zero
        
    - name: Run pytest
      env:
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        LOGS_FOLDER: ${{secrets.LOGS_FOLDER}}
        STAGE: ${{secrets.STAGE}}
      run: |
        pytest -v tests --cov --cov-report=xml --cov-report=html
